### ISSUE TITLE
heroku example

### ISSUE THREAD

**Issue by michael5wong** [jacobian/channels-example#9]
The heroku example (and clicking the deploy button) generates an Application Error?  Or am I missing something?  Thanks!

**Comment by rrmerugu** [comment]
Error:


Application Error
An error occurred in the application and your page could not be served. Please try again in a few moments.

If you are the application owner, check your logs for details.

**Comment by linshiyx** [comment]
@michael5wong 
in views.py
change _import haikunator_ to _from haikunator import Haikunator_
add _haikunator = Haikunator()_ before _label = haikunator.haikunate()_

**Comment by crcastle** [comment]
I don't think @linshiyx addresses the issue that most people are having here (including me), but I could be wrong, or maybe there are two issues.  I did the button deploy and here are my logs while trying to load the root URL of the app a few times.  It looks like the exception is coming from the worker dyno initially, but then from the web dyno.  What I don't understand is that about an hour later, I loaded the URL again and it worked fine.  @jacobian can you help me figure out what's going on here?

```
👉  h logs -t -a murmuring-crag-43643
2016-11-04T19:58:20.685957+00:00 heroku[api]: Enable Logplex by castle@heroku.com
2016-11-04T19:58:20.685957+00:00 heroku[api]: Release v2 created by castle@heroku.com
2016-11-04T19:58:21.359243+00:00 heroku[api]: Set SECRET_KEY config vars by castle@heroku.com
2016-11-04T19:58:21.359273+00:00 heroku[api]: Release v3 created by castle@heroku.com
2016-11-04T19:58:22.370290+00:00 heroku[api]: Attach DATABASE (@ref:postgresql-fitted-34831) by castle@heroku.com
2016-11-04T19:58:22.370290+00:00 heroku[api]: Release v4 created by castle@heroku.com
2016-11-04T19:58:23.873409+00:00 heroku[api]: Attach REDIS (@ref:redis-tetrahedral-98204) by castle@heroku.com
2016-11-04T19:58:23.873653+00:00 heroku[api]: Release v5 created by castle@heroku.com
2016-11-04T19:59:13.586306+00:00 heroku[api]: Scaled to web@1:Free worker@0:Free by castle@heroku.com
2016-11-04T19:59:13.589716+00:00 heroku[api]: Deploy by castle@heroku.com
2016-11-04T19:59:13.589851+00:00 heroku[api]: Release v6 created by castle@heroku.com
2016-11-04T19:59:14.154947+00:00 heroku[slug-compiler]: Slug compilation started
2016-11-04T19:59:14.154953+00:00 heroku[slug-compiler]: Slug compilation finished
2016-11-04T19:59:17.790014+00:00 heroku[web.1]: Starting process with command `daphne chat.asgi:channel_layer --port 45624 --bind 0.0.0.0 -v2`
2016-11-04T19:59:20.356487+00:00 app[web.1]: 2016-11-04 19:59:20,356 INFO     Starting server on 0.0.0.0:45624, channel layer chat.asgi:channel_layer
2016-11-04T19:59:21.440852+00:00 heroku[web.1]: State changed from starting to up
2016-11-04T19:59:38.839158+00:00 heroku[api]: Starting process with command `(python manage.py migrate); echo "469b8e789850d259fdf2ce385ad89d6b $?"` by castle@heroku.com
2016-11-04T19:59:43.754728+00:00 heroku[run.2326]: Awaiting client
2016-11-04T19:59:43.781228+00:00 heroku[run.2326]: Starting process with command `(python manage.py migrate); echo "469b8e789850d259fdf2ce385ad89d6b $?"`
2016-11-04T19:59:43.842823+00:00 heroku[run.2326]: State changed from starting to up
2016-11-04T19:59:46.768471+00:00 heroku[run.2326]: Process exited with status 0
2016-11-04T19:59:46.773604+00:00 heroku[run.2326]: State changed from up to complete
2016-11-04T19:59:47.258970+00:00 heroku[api]: Scaled to web@1:Free worker@1:Free by castle@heroku.com
2016-11-04T19:59:46.941624+00:00 heroku[web.1]: Restarting
2016-11-04T19:59:46.942346+00:00 heroku[web.1]: State changed from up to starting
2016-11-04T19:59:50.744826+00:00 heroku[web.1]: Stopping all processes with SIGTERM
2016-11-04T19:59:51.546000+00:00 heroku[web.1]: Starting process with command `daphne chat.asgi:channel_layer --port 15391 --bind 0.0.0.0 -v2`
2016-11-04T19:59:51.683160+00:00 heroku[web.1]: Process exited with status 0
2016-11-04T19:59:52.231332+00:00 heroku[worker.1]: Starting process with command `python manage.py runworker -v2`
2016-11-04T19:59:52.949181+00:00 heroku[worker.1]: State changed from starting to up
2016-11-04T19:59:54.206553+00:00 heroku[worker.1]: Process exited with status 1
2016-11-04T19:59:54.114677+00:00 app[worker.1]: 2016-11-04 19:59:54,114 - INFO - runworker - Running worker against backend default (asgi_redis.RedisChannelLayer)
2016-11-04T19:59:54.120057+00:00 app[worker.1]: Traceback (most recent call last):
2016-11-04T19:59:54.120058+00:00 app[worker.1]:   File "manage.py", line 8, in <module>
2016-11-04T19:59:54.120171+00:00 app[worker.1]:     execute_from_command_line(sys.argv)
2016-11-04T19:59:54.120199+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
2016-11-04T19:59:54.120294+00:00 app[worker.1]:     utility.execute()
2016-11-04T19:59:54.120315+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
2016-11-04T19:59:54.120400+00:00 app[worker.1]:     self.fetch_command(subcommand).run_from_argv(self.argv)
2016-11-04T19:59:54.120421+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
2016-11-04T19:59:54.120574+00:00 app[worker.1]:     self.execute(*args, **cmd_options)
2016-11-04T19:59:54.120600+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
2016-11-04T19:59:54.120698+00:00 app[worker.1]:     output = self.handle(*args, **options)
2016-11-04T19:59:54.120723+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/channels/management/commands/runworker.py", line 32, in handle
2016-11-04T19:59:54.120754+00:00 app[worker.1]:     Worker(channel_layer=self.channel_layer, callback=callback).run()
2016-11-04T19:59:54.120775+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/channels/worker.py", line 29, in run
2016-11-04T19:59:54.120799+00:00 app[worker.1]:     channel, content = self.channel_layer.receive_many(channels, block=True)
2016-11-04T19:59:54.120815+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/asgi_redis.py", line 110, in receive_many
2016-11-04T19:59:54.120856+00:00 app[worker.1]:     result = connection.blpop(list_names, timeout=self.blpop_timeout)
2016-11-04T19:59:54.120873+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/redis/client.py", line 1163, in blpop
2016-11-04T19:59:54.121121+00:00 app[worker.1]:     return self.execute_command('BLPOP', *keys)
2016-11-04T19:59:54.121122+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/redis/client.py", line 578, in execute_command
2016-11-04T19:59:54.121236+00:00 app[worker.1]:     connection.send_command(*args)
2016-11-04T19:59:54.121270+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/redis/connection.py", line 563, in send_command
2016-11-04T19:59:54.121379+00:00 app[worker.1]:     self.send_packed_command(self.pack_command(*args))
2016-11-04T19:59:54.121394+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/redis/connection.py", line 538, in send_packed_command
2016-11-04T19:59:54.121472+00:00 app[worker.1]:     self.connect()
2016-11-04T19:59:54.121474+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/redis/connection.py", line 442, in connect
2016-11-04T19:59:54.121540+00:00 app[worker.1]:     raise ConnectionError(self._error_message(e))
2016-11-04T19:59:54.121558+00:00 app[worker.1]: redis.exceptions.ConnectionError: Error 111 connecting to ec2-54-221-211-164.compute-1.amazonaws.com:13419. Connection refused.
2016-11-04T19:59:54.241301+00:00 heroku[worker.1]: State changed from up to crashed
2016-11-04T19:59:54.242361+00:00 heroku[worker.1]: State changed from crashed to starting
2016-11-04T19:59:55.296499+00:00 app[web.1]: 2016-11-04 19:59:55,296 INFO     Starting server on 0.0.0.0:15391, channel layer chat.asgi:channel_layer
2016-11-04T19:59:55.999326+00:00 heroku[web.1]: State changed from starting to up
2016-11-04T19:59:58.647181+00:00 heroku[worker.1]: Starting process with command `python manage.py runworker -v2`
2016-11-04T19:59:59.179487+00:00 heroku[worker.1]: State changed from starting to up
2016-11-04T20:00:00.910806+00:00 app[worker.1]: 2016-11-04 20:00:00,910 - INFO - runworker - Running worker against backend default (asgi_redis.RedisChannelLayer)
2016-11-04T20:00:00.916303+00:00 app[worker.1]: Traceback (most recent call last):
2016-11-04T20:00:00.916305+00:00 app[worker.1]:   File "manage.py", line 8, in <module>
2016-11-04T20:00:00.916334+00:00 app[worker.1]:     execute_from_command_line(sys.argv)
2016-11-04T20:00:00.916374+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
2016-11-04T20:00:00.916439+00:00 app[worker.1]:     utility.execute()
2016-11-04T20:00:00.916454+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
2016-11-04T20:00:00.916517+00:00 app[worker.1]:     self.fetch_command(subcommand).run_from_argv(self.argv)
2016-11-04T20:00:00.916520+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
2016-11-04T20:00:00.916584+00:00 app[worker.1]:     self.execute(*args, **cmd_options)
2016-11-04T20:00:00.916640+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
2016-11-04T20:00:00.916709+00:00 app[worker.1]:     output = self.handle(*args, **options)
2016-11-04T20:00:00.916724+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/channels/management/commands/runworker.py", line 32, in handle
2016-11-04T20:00:00.916765+00:00 app[worker.1]:     Worker(channel_layer=self.channel_layer, callback=callback).run()
2016-11-04T20:00:00.916769+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/channels/worker.py", line 29, in run
2016-11-04T20:00:00.916770+00:00 app[worker.1]:     channel, content = self.channel_layer.receive_many(channels, block=True)
2016-11-04T20:00:00.916771+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/asgi_redis.py", line 110, in receive_many
2016-11-04T20:00:00.916806+00:00 app[worker.1]:     result = connection.blpop(list_names, timeout=self.blpop_timeout)
2016-11-04T20:00:00.916807+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/redis/client.py", line 1163, in blpop
2016-11-04T20:00:00.916991+00:00 app[worker.1]:     return self.execute_command('BLPOP', *keys)
2016-11-04T20:00:00.916992+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/redis/client.py", line 578, in execute_command
2016-11-04T20:00:00.917067+00:00 app[worker.1]:     connection.send_command(*args)
2016-11-04T20:00:00.917068+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/redis/connection.py", line 563, in send_command
2016-11-04T20:00:00.917135+00:00 app[worker.1]:     self.send_packed_command(self.pack_command(*args))
2016-11-04T20:00:00.917149+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/redis/connection.py", line 538, in send_packed_command
2016-11-04T20:00:00.917236+00:00 app[worker.1]:     self.connect()
2016-11-04T20:00:00.917239+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/redis/connection.py", line 442, in connect
2016-11-04T20:00:00.917304+00:00 app[worker.1]:     raise ConnectionError(self._error_message(e))
2016-11-04T20:00:00.917323+00:00 app[worker.1]: redis.exceptions.ConnectionError: Error 111 connecting to ec2-54-221-211-164.compute-1.amazonaws.com:13419. Connection refused.
2016-11-04T20:00:01.014251+00:00 heroku[worker.1]: State changed from up to crashed
2016-11-04T20:00:01.007242+00:00 heroku[worker.1]: Process exited with status 1
2016-11-04T20:00:07.640307+00:00 heroku[router]: at=error code=H13 desc="Connection closed without response" method=GET path="/" host=murmuring-crag-43643.herokuapp.com request_id=0e602fc9-7865-4b32-9d0e-d2c15e51ee82 fwd="204.14.239.18" dyno=web.1 connect=0ms service=11ms status=503 bytes=0
2016-11-04T20:00:07.653353+00:00 app[web.1]: Unhandled Error
2016-11-04T20:00:07.653363+00:00 app[web.1]: Traceback (most recent call last):
2016-11-04T20:00:07.653367+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/twisted/python/log.py", line 101, in callWithLogger
2016-11-04T20:00:07.653370+00:00 app[web.1]:     return callWithContext({"system": lp}, func, *args, **kw)
2016-11-04T20:00:07.653371+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/twisted/python/log.py", line 84, in callWithContext
2016-11-04T20:00:07.653373+00:00 app[web.1]:     return context.call({ILogContext: newCtx}, func, *args, **kw)
2016-11-04T20:00:07.653374+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/twisted/python/context.py", line 118, in callWithContext
2016-11-04T20:00:07.653375+00:00 app[web.1]:     return self.currentContext().callWithContext(ctx, func, *args, **kw)
2016-11-04T20:00:07.653376+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/twisted/python/context.py", line 81, in callWithContext
2016-11-04T20:00:07.653377+00:00 app[web.1]:     return func(*args,**kw)
2016-11-04T20:00:07.653378+00:00 app[web.1]: --- <exception caught here> ---
2016-11-04T20:00:07.653379+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
2016-11-04T20:00:07.653379+00:00 app[web.1]:     why = selectable.doRead()
2016-11-04T20:00:07.653380+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/twisted/internet/tcp.py", line 209, in doRead
2016-11-04T20:00:07.653380+00:00 app[web.1]:     return self._dataReceived(data)
2016-11-04T20:00:07.653381+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/twisted/internet/tcp.py", line 215, in _dataReceived
2016-11-04T20:00:07.653382+00:00 app[web.1]:     rval = self.protocol.dataReceived(data)
2016-11-04T20:00:07.653383+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/twisted/protocols/basic.py", line 571, in dataReceived
2016-11-04T20:00:07.653383+00:00 app[web.1]:     why = self.lineReceived(line)
2016-11-04T20:00:07.653384+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/twisted/web/http.py", line 1701, in lineReceived
2016-11-04T20:00:07.653384+00:00 app[web.1]:     request = self.requestFactory(self, len(self.requests))
2016-11-04T20:00:07.653385+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/daphne/http_protocol.py", line 30, in __init__
2016-11-04T20:00:07.653387+00:00 app[web.1]:     self.reply_channel = self.factory.channel_layer.new_channel("!http.response.?")
2016-11-04T20:00:07.653387+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/asgi_redis.py", line 139, in new_channel
2016-11-04T20:00:07.653388+00:00 app[web.1]:     if not connection.exists(key):
2016-11-04T20:00:07.653388+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/redis/client.py", line 855, in exists
2016-11-04T20:00:07.653389+00:00 app[web.1]:     return self.execute_command('EXISTS', name)
2016-11-04T20:00:07.653390+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/redis/client.py", line 578, in execute_command
2016-11-04T20:00:07.653390+00:00 app[web.1]:     connection.send_command(*args)
2016-11-04T20:00:07.653391+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/redis/connection.py", line 563, in send_command
2016-11-04T20:00:07.653391+00:00 app[web.1]:     self.send_packed_command(self.pack_command(*args))
2016-11-04T20:00:07.653392+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/redis/connection.py", line 538, in send_packed_command
2016-11-04T20:00:07.653393+00:00 app[web.1]:     self.connect()
2016-11-04T20:00:07.653393+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/redis/connection.py", line 442, in connect
2016-11-04T20:00:07.653394+00:00 app[web.1]:     raise ConnectionError(self._error_message(e))
2016-11-04T20:00:07.653394+00:00 app[web.1]: redis.exceptions.ConnectionError: Error 111 connecting to ec2-54-221-211-164.compute-1.amazonaws.com:13419. Connection refused.
2016-11-04T20:00:07.653395+00:00 app[web.1]:
2016-11-04T20:00:08.507326+00:00 heroku[router]: at=error code=H13 desc="Connection closed without response" method=GET path="/favicon.ico" host=murmuring-crag-43643.herokuapp.com request_id=d6f14ca0-35dd-4944-877c-8007d44a8569 fwd="204.14.239.18" dyno=web.1 connect=2ms service=13ms status=503 bytes=0
2016-11-04T20:00:08.521603+00:00 app[web.1]: Unhandled Error
2016-11-04T20:00:08.521613+00:00 app[web.1]: Traceback (most recent call last):
2016-11-04T20:00:08.521614+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/twisted/python/log.py", line 101, in callWithLogger
2016-11-04T20:00:08.521615+00:00 app[web.1]:     return callWithContext({"system": lp}, func, *args, **kw)
2016-11-04T20:00:08.521616+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/twisted/python/log.py", line 84, in callWithContext
2016-11-04T20:00:08.521617+00:00 app[web.1]:     return context.call({ILogContext: newCtx}, func, *args, **kw)
2016-11-04T20:00:08.521618+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/twisted/python/context.py", line 118, in callWithContext
2016-11-04T20:00:08.521618+00:00 app[web.1]:     return self.currentContext().callWithContext(ctx, func, *args, **kw)
2016-11-04T20:00:08.521619+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/twisted/python/context.py", line 81, in callWithContext
2016-11-04T20:00:08.521620+00:00 app[web.1]:     return func(*args,**kw)
2016-11-04T20:00:08.521620+00:00 app[web.1]: --- <exception caught here> ---
2016-11-04T20:00:08.521621+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
2016-11-04T20:00:08.521622+00:00 app[web.1]:     why = selectable.doRead()
2016-11-04T20:00:08.521623+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/twisted/internet/tcp.py", line 209, in doRead
2016-11-04T20:00:08.521623+00:00 app[web.1]:     return self._dataReceived(data)
2016-11-04T20:00:08.521624+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/twisted/internet/tcp.py", line 215, in _dataReceived
2016-11-04T20:00:08.521625+00:00 app[web.1]:     rval = self.protocol.dataReceived(data)
2016-11-04T20:00:08.521625+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/twisted/protocols/basic.py", line 571, in dataReceived
2016-11-04T20:00:08.521626+00:00 app[web.1]:     why = self.lineReceived(line)
2016-11-04T20:00:08.521627+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/twisted/web/http.py", line 1701, in lineReceived
2016-11-04T20:00:08.521628+00:00 app[web.1]:     request = self.requestFactory(self, len(self.requests))
2016-11-04T20:00:08.521628+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/daphne/http_protocol.py", line 30, in __init__
2016-11-04T20:00:08.521629+00:00 app[web.1]:     self.reply_channel = self.factory.channel_layer.new_channel("!http.response.?")
2016-11-04T20:00:08.521630+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/asgi_redis.py", line 139, in new_channel
2016-11-04T20:00:08.521631+00:00 app[web.1]:     if not connection.exists(key):
2016-11-04T20:00:08.521631+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/redis/client.py", line 855, in exists
2016-11-04T20:00:08.521632+00:00 app[web.1]:     return self.execute_command('EXISTS', name)
2016-11-04T20:00:08.521632+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/redis/client.py", line 578, in execute_command
2016-11-04T20:00:08.521633+00:00 app[web.1]:     connection.send_command(*args)
2016-11-04T20:00:08.521634+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/redis/connection.py", line 563, in send_command
2016-11-04T20:00:08.521634+00:00 app[web.1]:     self.send_packed_command(self.pack_command(*args))
2016-11-04T20:00:08.521635+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/redis/connection.py", line 538, in send_packed_command
2016-11-04T20:00:08.521636+00:00 app[web.1]:     self.connect()
2016-11-04T20:00:08.521637+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/redis/connection.py", line 442, in connect
2016-11-04T20:00:08.521637+00:00 app[web.1]:     raise ConnectionError(self._error_message(e))
2016-11-04T20:00:08.521638+00:00 app[web.1]: redis.exceptions.ConnectionError: Error 111 connecting to ec2-54-221-211-164.compute-1.amazonaws.com:13419. Connection refused.
2016-11-04T20:00:08.521639+00:00 app[web.1]:
2016-11-04T20:00:26.237576+00:00 heroku[router]: at=error code=H13 desc="Connection closed without response" method=GET path="/" host=murmuring-crag-43643.herokuapp.com request_id=7a5b4e0d-335a-4c01-b83b-dfb922faae74 fwd="204.14.239.18" dyno=web.1 connect=1ms service=31ms status=503 bytes=0
2016-11-04T20:00:26.236099+00:00 app[web.1]: Unhandled Error
2016-11-04T20:00:26.236110+00:00 app[web.1]: Traceback (most recent call last):
2016-11-04T20:00:26.236111+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/twisted/python/log.py", line 101, in callWithLogger
2016-11-04T20:00:26.236112+00:00 app[web.1]:     return callWithContext({"system": lp}, func, *args, **kw)
2016-11-04T20:00:26.236112+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/twisted/python/log.py", line 84, in callWithContext
2016-11-04T20:00:26.236113+00:00 app[web.1]:     return context.call({ILogContext: newCtx}, func, *args, **kw)
2016-11-04T20:00:26.236114+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/twisted/python/context.py", line 118, in callWithContext
2016-11-04T20:00:26.236115+00:00 app[web.1]:     return self.currentContext().callWithContext(ctx, func, *args, **kw)
2016-11-04T20:00:26.236115+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/twisted/python/context.py", line 81, in callWithContext
2016-11-04T20:00:26.236116+00:00 app[web.1]:     return func(*args,**kw)
2016-11-04T20:00:26.236117+00:00 app[web.1]: --- <exception caught here> ---
2016-11-04T20:00:26.236118+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
2016-11-04T20:00:26.236118+00:00 app[web.1]:     why = selectable.doRead()
2016-11-04T20:00:26.236119+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/twisted/internet/tcp.py", line 209, in doRead
2016-11-04T20:00:26.236120+00:00 app[web.1]:     return self._dataReceived(data)
2016-11-04T20:00:26.236120+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/twisted/internet/tcp.py", line 215, in _dataReceived
2016-11-04T20:00:26.236121+00:00 app[web.1]:     rval = self.protocol.dataReceived(data)
2016-11-04T20:00:26.236122+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/twisted/protocols/basic.py", line 571, in dataReceived
2016-11-04T20:00:26.236122+00:00 app[web.1]:     why = self.lineReceived(line)
2016-11-04T20:00:26.236123+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/twisted/web/http.py", line 1701, in lineReceived
2016-11-04T20:00:26.236124+00:00 app[web.1]:     request = self.requestFactory(self, len(self.requests))
2016-11-04T20:00:26.236125+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/daphne/http_protocol.py", line 30, in __init__
2016-11-04T20:00:26.236126+00:00 app[web.1]:     self.reply_channel = self.factory.channel_layer.new_channel("!http.response.?")
2016-11-04T20:00:26.236127+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/asgi_redis.py", line 139, in new_channel
2016-11-04T20:00:26.236127+00:00 app[web.1]:     if not connection.exists(key):
2016-11-04T20:00:26.236128+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/redis/client.py", line 855, in exists
2016-11-04T20:00:26.236129+00:00 app[web.1]:     return self.execute_command('EXISTS', name)
2016-11-04T20:00:26.236129+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/redis/client.py", line 578, in execute_command
2016-11-04T20:00:26.236130+00:00 app[web.1]:     connection.send_command(*args)
2016-11-04T20:00:26.236131+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/redis/connection.py", line 563, in send_command
2016-11-04T20:00:26.236131+00:00 app[web.1]:     self.send_packed_command(self.pack_command(*args))
2016-11-04T20:00:26.236132+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/redis/connection.py", line 538, in send_packed_command
2016-11-04T20:00:26.236133+00:00 app[web.1]:     self.connect()
2016-11-04T20:00:26.236133+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/redis/connection.py", line 442, in connect
2016-11-04T20:00:26.236134+00:00 app[web.1]:     raise ConnectionError(self._error_message(e))
2016-11-04T20:00:26.236135+00:00 app[web.1]: redis.exceptions.ConnectionError: Error 111 connecting to ec2-54-221-211-164.compute-1.amazonaws.com:13419. Connection refused.
2016-11-04T20:00:26.236135+00:00 app[web.1]:
2016-11-04T20:00:27.206008+00:00 heroku[router]: at=error code=H13 desc="Connection closed without response" method=GET path="/favicon.ico" host=murmuring-crag-43643.herokuapp.com request_id=68277188-d8b4-4882-829d-493b6afc9946 fwd="204.14.239.18" dyno=web.1 connect=0ms service=15ms status=503 bytes=0```
